"use client";

import { Check, CheckCircle2, Clock3, ExternalLink, LoaderCircle, MoreHorizontal, Pencil, ShieldAlert, UserRound, X } from "lucide-react";
import { Badge, Button, Card } from "@/components/shared/ui";

export type QueueActionState = "idle" | "planning" | "ready" | "executing" | "complete" | "error";
export type QueueItemState = "open" | "in_progress" | "pending_approval" | "snoozed" | "dismissed" | "completed";
export type ActionPreviewData = {
  id: string; title: string; description: string; source: string; evidence: string;
  risk: "Low" | "Moderate" | "High"; confirmation: "Not required" | "Awaiting approval" | "Approved";
  category?: "recommendation" | "approval" | "reminder" | "report" | "blocked" | "milestone";
  state?: QueueItemState; assignee?: string | null; dueAt?: string | null; snoozedUntil?: string | null;
  integration?: string; unavailable?: boolean; resultLabel?: string; mode?: "internal" | "external" | "draft" | "read";
  changes?: string[]; status?: QueueActionState; result?: string; error?: string;
  onPreview?: () => void; onApprove?: () => void; onReject?: () => void; onEdit?: () => void; onSnooze?: () => void; onDismiss?: () => void; onReassign?: () => void;
};

function riskTone(risk: ActionPreviewData["risk"]): "success" | "warning" | "danger" { return risk === "Low" ? "success" : risk === "Moderate" ? "warning" : "danger"; }
function categoryTone(category?: ActionPreviewData["category"]): "neutral" | "success" | "warning" | "danger" | "info" { if (category === "approval") return "warning"; if (category === "reminder" || category === "blocked") return "danger"; if (category === "report") return "info"; if (category === "recommendation") return "success"; return "neutral"; }
function pretty(value?: string | null) { return value ? value.replaceAll("_", " ") : "Open"; }

export function ActionPreview({ action }: { action: ActionPreviewData }) {
  const busy = action.status === "planning" || action.status === "executing";
  const completed = action.state === "completed" || action.status === "complete";
  const dismissed = action.state === "dismissed";
  const canApprove = Boolean(action.onApprove) && !completed && !dismissed;
  const previewLabel = action.mode === "draft" ? "View draft" : action.mode === "read" ? "View plan" : "Preview action";
  return <Card className={`space-y-4 p-4 ${dismissed ? "opacity-65" : ""}`}>
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="mb-2 flex flex-wrap items-center gap-2"><Badge tone={categoryTone(action.category)}>{pretty(action.category || (action.mode === "draft" ? "draft" : "recommendation"))}</Badge><Badge tone={riskTone(action.risk)}>{action.risk} risk</Badge>{action.state && action.state !== "open" ? <Badge tone={action.state === "completed" ? "success" : action.state === "snoozed" ? "neutral" : "warning"}>{pretty(action.state)}</Badge> : null}</div><h3 className="font-medium text-[var(--ink)]">{action.title}</h3><p className="mt-1 text-sm text-[var(--ink-muted)]">{action.description}</p></div><MoreHorizontal className="h-5 w-5 text-[var(--ink-muted)]" aria-hidden="true" /></div>
    <div className="grid gap-3 text-sm sm:grid-cols-2"><div className="rounded-lg bg-[var(--surface-2)] p-3"><p className="text-xs font-medium uppercase tracking-wide text-[var(--ink-muted)]">Source</p><p className="mt-1 font-medium text-[var(--ink)]">{action.source}</p></div><div className="rounded-lg bg-[var(--surface-2)] p-3"><p className="text-xs font-medium uppercase tracking-wide text-[var(--ink-muted)]">Evidence</p><p className="mt-1 text-[var(--ink)]">{action.evidence}</p></div></div>
    {(action.assignee || action.dueAt || action.snoozedUntil) ? <div className="flex flex-wrap gap-x-4 gap-y-2 text-xs text-[var(--ink-muted)]">{action.assignee ? <span className="inline-flex items-center gap-1.5"><UserRound className="h-3.5 w-3.5" />{action.assignee}</span> : null}{action.dueAt ? <span className="inline-flex items-center gap-1.5"><Clock3 className="h-3.5 w-3.5" />Due {new Date(action.dueAt).toLocaleDateString()}</span> : null}{action.snoozedUntil ? <span>Snoozed until {new Date(action.snoozedUntil).toLocaleDateString()}</span> : null}</div> : null}
    {action.changes?.length ? <div className="rounded-lg border border-[var(--brand)]/20 bg-[var(--surface-2)] p-3 text-sm"><p className="font-medium text-[var(--ink)]">{action.mode === "draft" ? "Draft content" : "Evidence or next steps"}</p>{action.mode === "draft" ? <p className="mt-2 whitespace-pre-wrap text-[var(--ink-muted)]">{action.changes[0]}</p> : <ul className="mt-2 space-y-1 text-[var(--ink-muted)]">{action.changes.map((change) => <li key={change}>• {change}</li>)}</ul>}</div> : null}
    {action.unavailable ? <div className="rounded-lg border border-[var(--warning)]/25 bg-[#f3ead2]/55 p-3 text-sm text-[var(--ink)]"><span className="font-medium">{action.integration || "Integration"} is unavailable.</span> Hodi kept this as a reviewable plan.</div> : null}{action.result ? <div className="rounded-lg border border-[var(--success)]/25 bg-[var(--success)]/10 p-3 text-sm text-[var(--ink)]"><span className="font-medium">Result:</span> {action.result}</div> : null}{action.error ? <div role="alert" className="rounded-lg border border-[var(--danger)]/25 bg-[var(--danger)]/10 p-3 text-sm text-[var(--ink)]">{action.error}</div> : null}
    <div className="flex flex-wrap items-center justify-between gap-3 border-t border-[var(--border)] pt-3"><div className="flex items-center gap-2 text-sm text-[var(--ink-muted)]">{action.confirmation === "Approved" || action.confirmation === "Not required" || completed ? <CheckCircle2 className="h-4 w-4 text-[var(--success)]" /> : <ShieldAlert className="h-4 w-4 text-[var(--warning)]" />}<span>{completed ? "Completed" : action.confirmation}</span></div>{!completed && !dismissed ? <div className="flex flex-wrap items-center justify-end gap-2">{action.resultLabel ? <Button size="sm" variant="ghost" disabled title="Available when an action returns a link"><ExternalLink className="h-4 w-4" />{action.resultLabel}</Button> : null}{action.onEdit ? <Button size="sm" variant="secondary" onClick={action.onEdit} disabled={busy}><Pencil className="h-4 w-4" />Edit</Button> : null}{action.onReassign ? <Button size="sm" variant="ghost" onClick={action.onReassign} disabled={busy}><UserRound className="h-4 w-4" />Reassign</Button> : null}{action.onSnooze ? <Button size="sm" variant="ghost" onClick={action.onSnooze} disabled={busy}><Clock3 className="h-4 w-4" />Snooze</Button> : null}{action.onDismiss ? <Button size="sm" variant="ghost" onClick={action.onDismiss} disabled={busy}><X className="h-4 w-4" />Dismiss</Button> : null}{action.onReject ? <Button size="sm" variant="secondary" onClick={action.onReject} disabled={busy}><X className="h-4 w-4" />Reject</Button> : null}{canApprove ? <Button size="sm" onClick={action.onApprove} disabled={busy}>{action.status === "executing" ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}{action.category === "approval" ? "Approve" : "Approve & execute"}</Button> : null}{action.onPreview ? <Button size="sm" variant="secondary" onClick={action.onPreview} disabled={busy || action.unavailable}>{busy ? <LoaderCircle className="h-4 w-4 animate-spin" /> : null}{action.status === "ready" ? "Preview ready" : previewLabel}</Button> : null}</div> : <span className="text-xs text-[var(--ink-muted)]">No further action needed</span>}</div>
  </Card>;
}
