"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, BellRing, ClipboardCheck, LoaderCircle, RefreshCw, ShieldCheck, Sparkles, UserRound, type LucideIcon } from "lucide-react";
import { ActionPreview, type ActionPreviewData, type QueueItemState } from "@/components/hodi/ActionPreview";
import { Button, Input, PageHeader } from "@/components/shared/ui";

type QueueCategory = "recommendation" | "approval" | "reminder" | "report" | "blocked" | "milestone";
type QueueItem = ActionPreviewData & { category: QueueCategory; action?: string; payload?: Record<string, unknown>; approvalToken?: string };
type QueueResponse = { items?: unknown[]; queue?: unknown[]; data?: { items?: unknown[]; queue?: unknown[] }; meta?: { generatedAt?: string } };
type Tab = "all" | QueueCategory | "attention";
const tabs: Array<{ id: Tab; label: string }> = [{ id: "all", label: "All work" }, { id: "attention", label: "Needs attention" }, { id: "recommendation", label: "Recommendations" }, { id: "approval", label: "Approvals" }, { id: "reminder", label: "Reminders" }, { id: "report", label: "Reports" }];
const failText = (value: unknown) => value instanceof Error ? value.message : "Hodi could not complete that request.";
const risk = (value: unknown): ActionPreviewData["risk"] => value === "High" || value === "Moderate" ? value : "Low";
const stringOrNull = (value: unknown) => typeof value === "string" && value ? value : null;

function normalizeItem(raw: unknown): QueueItem | null {
  if (!raw || typeof raw !== "object") return null;
  const value = raw as Record<string, unknown>;
  const category = value.category === "approval" || value.category === "reminder" || value.category === "report" || value.category === "blocked" || value.category === "milestone" ? value.category : "recommendation";
  const state = value.state === "in_progress" || value.state === "pending_approval" || value.state === "snoozed" || value.state === "dismissed" || value.state === "completed" ? value.state : "open";
  return { id: String(value.id || value.queueItemId || ""), title: String(value.title || "Untitled work item"), description: String(value.description || value.summary || "No description provided."), source: String(value.source || "Boatship workspace"), evidence: String(value.evidence || "Recorded project context"), risk: risk(value.risk), confirmation: value.confirmation === "Approved" || value.confirmation === "Awaiting approval" ? value.confirmation : "Not required", category, state: state as QueueItemState, assignee: stringOrNull(value.assignee || value.assigneeName), dueAt: stringOrNull(value.dueAt || value.dueDate), snoozedUntil: stringOrNull(value.snoozedUntil), integration: stringOrNull(value.integration) || undefined, unavailable: value.unavailable === true, resultLabel: stringOrNull(value.resultLabel) || undefined, mode: value.mode === "internal" || value.mode === "external" || value.mode === "draft" ? value.mode : "read", changes: Array.isArray(value.changes) ? value.changes.map(String) : undefined, status: value.status === "planning" || value.status === "ready" || value.status === "executing" || value.status === "complete" || value.status === "error" ? value.status : "idle", result: stringOrNull(value.result) || undefined, error: stringOrNull(value.error) || undefined, action: stringOrNull(value.action) || undefined, payload: value.payload && typeof value.payload === "object" ? value.payload as Record<string, unknown> : undefined, approvalToken: stringOrNull(value.approvalToken) || undefined };
}

function extractItems(data: QueueResponse) { const raw = data.items || data.queue || data.data?.items || data.data?.queue || []; return Array.isArray(raw) ? raw.map(normalizeItem).filter((item): item is QueueItem => Boolean(item?.id)) : []; }

export function HodiDashboard() {
  const [items, setItems] = useState<QueueItem[]>([]); const [tab, setTab] = useState<Tab>("all"); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [lastSync, setLastSync] = useState<string | null>(null); const requestVersion = useRef(0);
  const refresh = useCallback(async () => { const version = ++requestVersion.current; setLoading(true); setError(null); try { const response = await fetch("/api/hodi/queue", { cache: "no-store", headers: { Accept: "application/json" } }); const data = await response.json().catch(() => ({})) as QueueResponse & { error?: string }; if (!response.ok) throw new Error(data.error || "Could not load the persistent Hodi queue."); if (version !== requestVersion.current) return; setItems(extractItems(data)); setLastSync(data.meta?.generatedAt || new Date().toISOString()); } catch (reason) { if (version === requestVersion.current) setError(failText(reason)); } finally { if (version === requestVersion.current) setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void refresh(); }, 0); return () => window.clearTimeout(timer); }, [refresh]);
  const mutate = useCallback(async (id: string, patch: Record<string, unknown>) => { setItems((current) => current.map((item) => item.id === id ? { ...item, ...patch, status: "executing" } : item)); try { const response = await fetch(`/api/hodi/queue/${encodeURIComponent(id)}`, { method: "PATCH", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify(patch) }); const data = await response.json().catch(() => ({})) as QueueResponse & { item?: unknown; error?: string }; if (!response.ok) throw new Error(data.error || "Could not update this queue item."); const updated = normalizeItem(data.item || (data.items && data.items[0])); if (updated) setItems((current) => current.map((item) => item.id === id ? updated : item)); else await refresh(); } catch (reason) { setError(failText(reason)); await refresh(); } }, [refresh]);
  const visible = useMemo(() => items.filter((item) => { const attention = item.category === "approval" || item.category === "reminder" || item.category === "blocked" || item.state === "pending_approval"; const matchesTab = tab === "all" || (tab === "attention" ? attention : item.category === tab); const needle = search.trim().toLowerCase(); const matchesSearch = !needle || `${item.title} ${item.description} ${item.source} ${item.assignee || ""}`.toLowerCase().includes(needle); return matchesTab && matchesSearch && item.state !== "dismissed"; }), [items, search, tab]);
  const counts = useMemo(() => ({ all: items.filter((item) => item.state !== "dismissed").length, attention: items.filter((item) => item.state !== "dismissed" && (item.category === "approval" || item.category === "reminder" || item.category === "blocked" || item.state === "pending_approval")).length, recommendation: items.filter((item) => item.category === "recommendation" && item.state !== "dismissed").length, approval: items.filter((item) => item.category === "approval" && item.state !== "dismissed").length, reminder: items.filter((item) => item.category === "reminder" && item.state !== "dismissed").length, report: items.filter((item) => item.category === "report" && item.state !== "dismissed").length, blocked: items.filter((item) => item.category === "blocked" && item.state !== "dismissed").length, milestone: items.filter((item) => item.category === "milestone" && item.state !== "dismissed").length }), [items]);
  const actionProps = (item: QueueItem): ActionPreviewData => ({ ...item, onApprove: () => void mutate(item.id, { state: "completed", decision: "approved" }), onReject: item.category === "approval" ? () => void mutate(item.id, { state: "open", decision: "rejected" }) : undefined, onEdit: () => void mutate(item.id, { state: "in_progress" }), onSnooze: () => void mutate(item.id, { state: "snoozed", snoozedUntil: new Date(Date.now() + 86400000).toISOString() }), onDismiss: () => void mutate(item.id, { state: "dismissed" }), onReassign: () => void mutate(item.id, { state: "in_progress", reassignRequested: true }) });
  const summary: Array<[string, number, LucideIcon]> = [["All work", counts.all, ClipboardCheck], ["Needs attention", counts.attention, BellRing], ["Approvals", counts.approval, ShieldCheck], ["Reminders", counts.reminder, UserRound]];
  const activeTabs = tabs.filter((item) => item.id === "all" || item.id === tab || counts[item.id] > 0);

  return <div className="mx-auto max-w-7xl space-y-7">
    <PageHeader title="Hodi work queue" description="Review recommendations, approvals, reminders, and reports in one place." actions={<>
      <Button variant="secondary" onClick={() => void refresh()} disabled={loading}><RefreshCw className={loading ? "h-4 w-4 animate-spin" : "h-4 w-4"} />{loading ? "Refreshing" : "Refresh queue"}</Button>
      {!loading && counts.all > 0 ? <Link href="/agent" className="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-[var(--brand)] px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-[var(--brand-strong)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--brand)]">Chat with Hodi <ArrowRight className="h-4 w-4" /></Link> : null}
    </>} />
    {error ? <div role="alert" className="rounded-xl border border-[var(--warning)]/30 bg-[#f3ead2]/55 p-4 text-sm text-[var(--ink)]">{error} <button className="ml-2 underline underline-offset-2" onClick={() => void refresh()}>Try again</button></div> : null}
    {loading ? <div role="status" className="flex items-center gap-3 py-12 text-sm text-[var(--ink-muted)]"><LoaderCircle className="h-5 w-5 animate-spin text-[var(--brand)]" />Loading Hodi work queue…</div> : null}
    {!loading && !error && counts.all === 0 ? <section className="mx-auto flex max-w-2xl flex-col items-center px-4 py-14 text-center sm:py-20">
      <span className="mb-7 flex h-14 w-14 items-center justify-center rounded-2xl bg-[var(--accent-soft)] text-[var(--brand)]"><Sparkles className="h-7 w-7" /></span>
      <h2 className="font-[family-name:var(--font-display)] text-3xl text-[var(--ink)] sm:text-4xl">Your work queue is clear</h2>
      <p className="mt-3 max-w-prose text-base leading-7 text-[var(--ink-muted)]">When Hodi has recommendations, approvals, reminders, or reports for you, they&apos;ll appear here. Open a conversation to ask about your workspace or plan the next step.</p>
      <Link href="/agent" className="mt-7 inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-[var(--brand)] px-5 py-2.5 text-sm font-medium text-white transition-colors hover:bg-[var(--brand-strong)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--brand)]">Start a conversation <ArrowRight className="h-4 w-4" /></Link>
      {lastSync ? <p className="mt-8 text-xs text-[var(--ink-muted)]">Last checked {new Date(lastSync).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p> : null}
    </section> : null}
    {!loading && counts.all > 0 ? <>
      <section aria-label="Queue summary" className="grid grid-cols-2 gap-x-6 gap-y-5 border-y border-[var(--border)] py-5 lg:grid-cols-4">
        {summary.map(([label, value, Icon]) => <div key={label} className="flex items-center gap-3"><Icon className="h-5 w-5 shrink-0 text-[var(--brand)]" /><div><p className="font-[family-name:var(--font-display)] text-2xl leading-none text-[var(--ink)] tabular-nums">{value}</p><p className="mt-1 text-sm text-[var(--ink-muted)]">{label}</p></div></div>)}
      </section>
      <section className="space-y-5">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-[family-name:var(--font-display)] text-2xl text-[var(--ink)]">Work queue</h2><p className="mt-1 text-sm text-[var(--ink-muted)]">Review each item and decide what happens next.</p></div>{lastSync ? <p className="text-xs text-[var(--ink-muted)]">Synced {new Date(lastSync).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</p> : null}</div>
        <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2" aria-label="Queue views">{activeTabs.map((item) => <Button key={item.id} size="sm" variant={tab === item.id ? "primary" : "secondary"} aria-pressed={tab === item.id} onClick={() => setTab(item.id)}>{item.label} <span className="opacity-70">{counts[item.id]}</span></Button>)}</div><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search queue" aria-label="Search queue" className="lg:max-w-xs" /></div>
        {visible.length ? <div className="grid gap-4 lg:grid-cols-2">{visible.map((item) => <ActionPreview key={item.id} action={actionProps(item)} />)}</div> : <div className="border-t border-[var(--border)] py-10 text-center"><p className="font-medium text-[var(--ink)]">No matching work</p><p className="mt-1 text-sm text-[var(--ink-muted)]">Clear your search or choose another queue view.</p><Button className="mt-4" variant="secondary" onClick={() => { setSearch(""); setTab("all"); }}>Show all work</Button></div>}
      </section>
    </> : null}
  </div>;
}
